[package]
name = "client"
description = "client"
version = "0.1.0"
authors = ["bakape <bakape@gmail.com>"]
categories = ["wasm"]
readme = "README.md"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.54"
protocol = { path = "../protocol" }
js-sys = "0.3.32"
wasm-bindgen-futures = "0.4.6"
serde = "1.0.104"
serde_json = "1.0.44"
flate2 = "1.0.13"
base64 = "0.11.0"
yew = "0.11.0"
stdweb = "0.4.20"
failure = "0.1.6"

[dependencies.web-sys]
version = "0.3.31"
features = [
  'Document',
  'Window',
  'HtmlElement',
  'Element',
  'Node',
  "NodeList",
  "console",
  "CloseEvent",
  "ErrorEvent",
  "MessageEvent",
  "WebSocket",
  "Location",
  "Navigator",
  "EventTarget",
  "AddEventListenerOptions",
  "Event",
  "Storage",
  "Crypto",
  "BinaryType",
]

[dev-dependencies]
wasm-bindgen-test = "0.3.4"
futures = "0.3.1"
js-sys = "0.3.31"
wasm-bindgen-futures = "0.4.4"
