[package]
name = "client"
description = "client"
version = "0.1.0"
authors = ["bakape <bakape@gmail.com>"]
categories = ["wasm"]
readme = "README.md"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.54"
protocol = { path = "../protocol" }
js-sys = "0.3.32"
wasm-bindgen-futures = "0.4.6"
serde = "1.0.104"
serde_json = "1.0.48"
flate2 = "1.0.13"
base64 = "0.12.0"
yew = { version = "0.13.2", features = ["web_sys"] }
hex = "0.4.2"
anyhow = "1.0.26"

[dependencies.web-sys]
version = "0.3.36"
features = [
  'Document',
  'Window',
  'HtmlElement',
  'Element',
  'Node',
  "NodeList",
  "console",
  "CloseEvent",
  "ErrorEvent",
  "MessageEvent",
  "WebSocket",
  "Location",
  "Navigator",
  "EventTarget",
  "AddEventListenerOptions",
  "Event",
  "Storage",
  "Crypto",
  "BinaryType",
  "FormData",
  "HtmlFormElement",
  "HtmlAnchorElement",
  "HtmlAudioElement",
]

[dev-dependencies]
wasm-bindgen-test = "0.3.9"
futures = "0.3.4"
js-sys = "0.3.31"
wasm-bindgen-futures = "0.4.9"

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = false
