[package]
name = "client"
description = "client"
version = "0.1.0"
authors = ["bakape <bakape@gmail.com>"]
categories = ["wasm"]
readme = "README.md"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.54"
protocol = { path = "../protocol" }
js-sys = "0.3.32"
serde = { version = "1.0.104", features = ["rc"] }
serde_json = "1.0.51"
flate2 = "1.0.13"
base64 = "0.12.0"
yew = { version = "0.14.3", features = ["web_sys"] }
hex = "0.4.2"
anyhow = "1.0.28"
wasm-bindgen-futures = "0.4.10"
console_error_panic_hook = "0.1.6"

[dependencies.web-sys]
version = "0.3.36"
features = [
  'Document',
  'Window',
  'HtmlElement',
  'Element',
  'Node',
  "NodeList",
  "console",
  "CloseEvent",
  "ErrorEvent",
  "MessageEvent",
  "WebSocket",
  "Location",
  "Navigator",
  "EventTarget",
  "AddEventListenerOptions",
  "Event",
  "Storage",
  "Crypto",
  "BinaryType",
  "FormData",
  "HtmlFormElement",
  "HtmlAnchorElement",
  "HtmlAudioElement",
  "UrlSearchParams",
  "History",
  "ScrollRestoration",
]

[profile.release]
opt-level = "z"
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = false
