version: "3"
services:
  meguca:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - images:/meguca/images
      - videos:/meguca/www/videos
    depends_on:
      - postgres
  postgres:
    image: postgres:12
    restart: always
    shm_size: "256MB"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=meguca
      - POSTGRES_PASSWORD=meguca
      - POSTGRES_DB=meguca
volumes:
  images:
  db:
  videos:
