[package]
name = "server"
version = "0.1.0"
authors = ["bakape <bakape@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "1.0.8"
diesel = { version = "1.4.3", features = ["postgres"] }
image = "0.22.3"
actix-files = "0.1.7"
env_logger = "0.7.1"
serde = "1.0.102"
serde_json = "1.0.41"

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = false
