[package]
name = "websockets"
version = "0.1.0"
authors = ["bakape <bakape@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[dependencies]
libc = "0.2.68"
rayon = "1.2.1"
protocol = { path = "../../protocol" }
serde = { version = "1.0.103", features = ["derive"] }
serde_json = "1.0.51"
heapless = "0.5.1"
backtrace = "0.3.46"
uuid = "0.8.1"
openssl = { version = "0.10.29", features = ["vendored"] }
