[package]
name = "websockets"
version = "0.1.0"
authors = ["bakape <bakape@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[dependencies]
libc = "0.2.65"
rayon = "1.2.1"
protocol = { path = "../../protocol" }
serde = { version = "1.0.103", features = ["derive"]}
serde_json = "1.0.44"
heapless = "0.5.1"
backtrace = "0.3.42"
